version: '3.3'
services:
  database:
    container_name: influxdb
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    build:
      context: .
      dockerfile: services/influx/Dockerfile
    env_file:
      - services/influx/env_variables
    networks:
      default:
        aliases:
          - influxdb

  broker:
    container_name: rabbit
    image: rabbit
    restart: always
    ports:
      - "1883:1883"
      - "15672:15672"
      - "5672:5672"
    build:
      context: .
      dockerfile: services/rabbit/Dockerfile
    networks:
      default:
        aliases:
          - rabbit
  
  visualizer:
    container_name: grafana
    image: grafana_image
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: services/grafana/Dockerfile

  telegraf:
    container_name: telegraf
    image: telegraf:1.25.0
    restart: always
    build:
      context: .
      dockerfile: services/telegraf/Dockerfile    
    depends_on:
      - database
      - broker
  
  analytics:
    container_name: analitica
    image: analitica_image
    restart: always
    build:
      context: .
      dockerfile: services/analytics/Dockerfile.back
    depends_on:
      - database
      - broker
      - telegraf

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"



